#!/usr/bin/env python
# -*- coding:utf-8 -*-

import sys, geoclueproperties.geoclue_properties

try:
    sys.exit(geoclueproperties.geoclue_properties.main())
except KeyboardInterrupt:
    sys.exit(1)
